### ISSUE TITLE
Weekly Log For Amir Sagiv

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1368]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [amirsagiv83](https://github.com/amirsagiv83)**
_Thursday Mar 23, 2017 at 19:05 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/122_

----

**Comment by RoeyMaor** [comment]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amirsagiv83](https://github.com/amirsagiv83)**
_Saturday Mar 25, 2017 at 11:29 GMT_

----

Weekly log for week 1 (19.3-25.3):

- [x]  Organizing a meeting to make sure we don't waste the first week.
- [x]  Managing a vacations issue.
- [x]  Making sure Plugin works and runs on different OS.
- [x]  tried to solve the read - only problem in the SpartanizerUtils class.

**Comment by RoeyMaor** [comment]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amirsagiv83](https://github.com/amirsagiv83)**
_Saturday Apr 01, 2017 at 10:12 GMT_

----

Weekly log for week 2 (26.3-1.4):

- [x] Started to implement our new Leonidas with Sharon and Michal.

- [x] took part in the meeting with Yossi on building Leonidas.

- [x] Managed Issues and vacations.

- [x] Managing and completing my part in analyzing tippers #138, also helped with Roey's part since he is on vacation.

- [x] Started working on GUI and created and example to the controller we want to implement. #139

- [x] Created a wiki on JavaFX and how to use it with IntelliJ : [link](https://github.com/TechnionYP5777/IntelliJ-Spartanizer/wiki/Introduction-To-JavaFX)

**Comment by RoeyMaor** [comment]
<a href="https://github.com/yossigil"><img src="https://avatars2.githubusercontent.com/u/12775400?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yossigil](https://github.com/yossigil)**
_Saturday Apr 01, 2017 at 10:14 GMT_

----

:100:

**Comment by RoeyMaor** [comment]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amirsagiv83](https://github.com/amirsagiv83)**
_Wednesday Apr 12, 2017 at 11:55 GMT_

----

Weekly log for week 3 (2.4 - 8.4):

- [x] Took part in a GUI team meeting

- [x] Studied Zahi's wiki on JavaFX as asked.

- [x] Arranged GUI missions

- [x] Managed issues

- [x] Developed a prototype of the toolbox controller #166 

- [x] Created the reports project on Github and managed it.

- [x] Closed issues #152 and #151

**Comment by RoeyMaor** [comment]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amirsagiv83](https://github.com/amirsagiv83)**
_Friday Apr 21, 2017 at 13:11 GMT_

----

Weekly log for week 4 (18.4 - 22.4 {short week due to Passover}):

- [x] Took part in a team meeting on Tuesday.

- [x] completed the no printout tests issue. #163 

- [x] Spartanized the whole Project. #168 

- [x] Managed issues and cards.

- [x] Helped issue #170 by finding a way to load the project in eclipse by using a Gradle plugin.

- [x] Created the presentation for next week. #156 

- [x] worked with Michal on solving the bug discussed on issue #171

**Comment by RoeyMaor** [comment]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amirsagiv83](https://github.com/amirsagiv83)**
_Saturday Apr 29, 2017 at 13:39 GMT_

----

Weekly log for week 4 (23.4 - 29.4):

- [x] Took part in the lectures on Sunday and Monday.

- [x] Created Leonidas menu bar in IntelliJ. #175

- [x] Created toolBox controller GUI in Swing instead of JAVAFX. #174  

- [x] Managed issues and cards.

- [x] Created an ABOUT window for our plugin. #181 

- [x] Continued developing the toolbox controller GUI. #166

**Comment by RoeyMaor** [comment]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amirsagiv83](https://github.com/amirsagiv83)**
_Saturday May 06, 2017 at 11:59 GMT_

----

Weekly log for week 5 (30.4 - 6.5):

- [x] Created 'name' methods to all tippers. #176

- [x] Developed the engine for the toolbox controller and made it work properly. #166   

- [x] Managed issues and cards.

- [x] Added functionalities for the Toolbox class. 

- [x] Wrote tests for GenericPsiStatement. #185 

- [x] Wrote tests for ToolBox. #191

**Comment by RoeyMaor** [comment]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amirsagiv83](https://github.com/amirsagiv83)**
_Sunday May 14, 2017 at 07:23 GMT_

----

Weekly log for week 6 (7.5 - 13.5):

On Vacation.

**Comment by RoeyMaor** [comment]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amirsagiv83](https://github.com/amirsagiv83)**
_Saturday May 20, 2017 at 20:52 GMT_

----

Weekly log for week 7 (14.5 - 20.5):

- [x] Worked on the new Toolbox Controller. #222 

- [x] Implemented a generic components JTable. #224 

- [x] Managed issues and cards.

- [x] Added functionalities for the Toolbox class. 

- [x] Fixed a bug in the menu bar. #228

**Comment by amirsagiv83** [comment]
Weekly log for week 8 (21.5 - 27.5):

- [x] Worked with Anna and Michal on on the new Toolbox Controller. #1388 

- [x] searched for ways to save data between runs. #1390 

- [x] Managed issues and cards in the new repo and project..

- [x] Worked with Michal on changing the engine to work with forests instead of trees.

- [x] Created and implemented an Identifier basic block and added constraints methods.

**Comment by amirsagiv83** [comment]
Weekly log for week 9 (28.5 - 3.6):

- [x] Worked with Michal on Fluent setter #1436 

- [x] Worked with Michal on Class basic block. #1387 

- [x] Fixed bug on cent tipper. #1443 

- [x] Fixed bug with nano patterns.

- [x] Updated ReadMe file.

- [x] Created a file for live testing. #1444 

- [x] Managed to save info about active tippers between runs. #1390 

- [x] Managed issues and cards in the new repo and project..

**Comment by amirsagiv83** [comment]
Weekly log for week 10 (4.6 - 10.6):

- [x] Added Icons to Leonidas Menu. #1471  

- [x] Added a pop-up dialog to provide info on nano patterns. #1470

- [x] Fixed the clean button in playground. #1466 

- [x] Added explanations for nano patterns in user guide. #1465 

- [x] closed issue #1464 

- [x] Added Examples to Controller toolbox GUI. #1388 

- [ ] Worked on issue #1467 and found a library that will solve it.

- [x] Managed issues and cards in the repository and project.

**Comment by amirsagiv83** [comment]
Weekly log for week 11 (11.6 - 17.6):

On Vacation.

**Comment by amirsagiv83** [comment]
Weekly log for week 12 (18.6 - 24.6):

- [x] Fixed examples for ToolBoxController GUI #1508  

- [x] Writing tests examples for tippers. #1511 

- [x] Updates wikis #1519 

- [x] Created new interactive GUI feature that shows the user all available tipper for a file. #1528 

- [x] Fixed a bug in nano patterns pop up. #1521 

- [x] Fixed bugs in cent tipper. #1540 

- [x] Built the edit tipper GUI 🎉 with all needed functionalities! #1388 

- [x] Managed issues and cards in the repository and project.

- [x] Started working on issue #1541

**Comment by amirsagiv83** [comment]
Weekly log for week 13 (26.6 - 1.7):

- [x] Added 3 new tippers

- [x] fixed bugs in older tippers

- [x] Updated wikis and created an organized wiki with all the information needed for users and developers.

- [x] Added tests to increase codecov

- [x] Fixed bug in ToolBox controller.

- [x] Managed issues and cards in the repository and project.

- [x] Managed all the finishes needed to be done in the project with everyone.
